
/*
================================================================================
Filterscript generated using Madon Gangsta TextDraw Editor Version 2012.
Designed for SA-MP 0.3b.
================================================================================
Time and Date: 2012-2-28 @ 11:42:4

Instructions:
1- Compile this file using the compiler provided with the sa-mp server package.
2- Copy the .amx file to the filterscripts directory.
3- Add the filterscripts in the server.cfg file (more info here:
http://wiki.sa-mp.com/wiki/Server.cfg)
4- Run the server!

Disclaimer:
You have full rights over this file. You can distribute it, modify it, and
change it as much as you want, without having to give any special credits.
*/

#include <a_samp>

new Text:Textdraw0;
new Text:Textdraw1;
new Text:Textdraw2;
new Text:Textdraw3;
new Text:Textdraw4;
new Text:Textdraw5;
new Text:Textdraw6;
new Text:Textdraw7;

public OnFilterScriptInit()
{
   	print("Textdraw file generated by");
   	print("Zamaroht's textdraw editor was loaded.");

	Textdraw0 = TextDrawCreate(637.314819, 1.500000, "usebox");
	TextDrawLetterSize(Textdraw0, 0.000000, 1.951851);
	TextDrawTextSize(Textdraw0, -2.000000, 0.000000);
	TextDrawAlignment(Textdraw0, 1);
	TextDrawColor(Textdraw0, 0);
	TextDrawUseBox(Textdraw0, true);
	TextDrawBoxColor(Textdraw0, 255);
	TextDrawSetShadow(Textdraw0, 0);
	TextDrawSetOutline(Textdraw0, 0);
	TextDrawFont(Textdraw0, 0);

	Textdraw1 = TextDrawCreate(640.594482, 1.500000, "usebox");
	TextDrawLetterSize(Textdraw1, 0.000000, 8.632577);
	TextDrawTextSize(Textdraw1, -2.000000, 0.000000);
	TextDrawAlignment(Textdraw1, 1);
	TextDrawColor(Textdraw1, 0);
	TextDrawUseBox(Textdraw1, true);
	TextDrawBoxColor(Textdraw1, 102);
	TextDrawSetShadow(Textdraw1, 0);
	TextDrawSetOutline(Textdraw1, 0);
	TextDrawFont(Textdraw1, 0);

	Textdraw2 = TextDrawCreate(642.468444, 78.499992, "usebox");
	TextDrawLetterSize(Textdraw2, 0.000000, 0.072222);
	TextDrawTextSize(Textdraw2, -1.062957, 0.000000);
	TextDrawAlignment(Textdraw2, 1);
	TextDrawColor(Textdraw2, 0);
	TextDrawUseBox(Textdraw2, true);
	TextDrawBoxColor(Textdraw2, 255);
	TextDrawSetShadow(Textdraw2, 0);
	TextDrawSetOutline(Textdraw2, 0);
	TextDrawFont(Textdraw2, 0);

	Textdraw3 = TextDrawCreate(641.531494, 426.166687, "usebox");
	TextDrawLetterSize(Textdraw3, 0.000000, 2.211111);
	TextDrawTextSize(Textdraw3, -2.000000, 0.000000);
	TextDrawAlignment(Textdraw3, 1);
	TextDrawColor(Textdraw3, 0);
	TextDrawUseBox(Textdraw3, true);
	TextDrawBoxColor(Textdraw3, 255);
	TextDrawSetShadow(Textdraw3, 0);
	TextDrawSetOutline(Textdraw3, 0);
	TextDrawFont(Textdraw3, 0);

	Textdraw4 = TextDrawCreate(641.531494, 383.000183, "usebox");
	TextDrawLetterSize(Textdraw4, 0.000000, 9.405554);
	TextDrawTextSize(Textdraw4, -1.999999, 0.000000);
	TextDrawAlignment(Textdraw4, 1);
	TextDrawColor(Textdraw4, 0);
	TextDrawUseBox(Textdraw4, true);
	TextDrawBoxColor(Textdraw4, 102);
	TextDrawSetShadow(Textdraw4, 0);
	TextDrawSetOutline(Textdraw4, 0);
	TextDrawFont(Textdraw4, 0);

	Textdraw5 = TextDrawCreate(640.594482, 382.416839, "usebox");
	TextDrawLetterSize(Textdraw5, 0.000000, -0.057409);
	TextDrawTextSize(Textdraw5, -1.062957, 0.000000);
	TextDrawAlignment(Textdraw5, 1);
	TextDrawColor(Textdraw5, 0);
	TextDrawUseBox(Textdraw5, true);
	TextDrawBoxColor(Textdraw5, 255);
	TextDrawSetShadow(Textdraw5, 0);
	TextDrawSetOutline(Textdraw5, 0);
	TextDrawFont(Textdraw5, 0);

	Textdraw6 = TextDrawCreate(484.451110, 47.833354, "Cops And Robbers");
	TextDrawLetterSize(Textdraw6, 0.641625, 2.416666);
	TextDrawAlignment(Textdraw6, 1);
	TextDrawColor(Textdraw6, -16776961);
	TextDrawSetShadow(Textdraw6, 0);
	TextDrawSetOutline(Textdraw6, 1);
	TextDrawBackgroundColor(Textdraw6, 51);
	TextDrawFont(Textdraw6, 0);
	TextDrawSetProportional(Textdraw6, 1);

	Textdraw7 = TextDrawCreate(3.748062, 382.666748, "www.czcnr.ml");
	TextDrawLetterSize(Textdraw7, 0.581185, 2.247500);
	TextDrawAlignment(Textdraw7, 1);
	TextDrawColor(Textdraw7, -1061109505);
	TextDrawSetShadow(Textdraw7, 0);
	TextDrawSetOutline(Textdraw7, 1);
	TextDrawBackgroundColor(Textdraw7, 51);
	TextDrawFont(Textdraw7, 3);
	TextDrawSetProportional(Textdraw7, 1);

	return 1;
}

public OnFilterScriptExit()
{
   TextDrawHideForAll(Textdraw0);
   TextDrawDestroy(Textdraw0);
   TextDrawHideForAll(Textdraw1);
   TextDrawDestroy(Textdraw1);
   TextDrawHideForAll(Textdraw2);
   TextDrawDestroy(Textdraw2);
   TextDrawHideForAll(Textdraw3);
   TextDrawDestroy(Textdraw3);
   TextDrawHideForAll(Textdraw4);
   TextDrawDestroy(Textdraw4);
   TextDrawHideForAll(Textdraw6);
   TextDrawDestroy(Textdraw6);
   TextDrawHideForAll(Textdraw7);
   TextDrawDestroy(Textdraw7);
   return 1;
}

public OnPlayerRequestClass(playerid, classid)
{
   TextDrawShowForPlayer(playerid, Textdraw0);
   TextDrawShowForPlayer(playerid, Textdraw1);
   TextDrawShowForPlayer(playerid, Textdraw2);
   TextDrawShowForPlayer(playerid, Textdraw3);
   TextDrawShowForPlayer(playerid, Textdraw4);
   TextDrawShowForPlayer(playerid, Textdraw6);
   TextDrawShowForPlayer(playerid, Textdraw7);
   return 1;
}

public OnPlayerSpawn(playerid)
{
   TextDrawHideForPlayer(playerid, Textdraw0);
   TextDrawHideForPlayer(playerid, Textdraw1);
   TextDrawHideForPlayer(playerid, Textdraw2);
   TextDrawHideForPlayer(playerid, Textdraw3);
   TextDrawHideForPlayer(playerid, Textdraw4);
   TextDrawHideForPlayer(playerid, Textdraw6);
   TextDrawHideForPlayer(playerid, Textdraw7);
   return 1;
}


